services:
  - type: web
    name: organiza-plus
    env: docker
    repo: https://github.com/paulojr611/organiza-plus
    branch: main
    rootDir: backend
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:+zgHD3mOTwK4LcrbgsfZ7bk0ukACtSSPdcstAyOMYkA=
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: organiza_plus
      - key: DB_USERNAME
        value: user
      - key: DB_PASSWORD
        value: password
